language: node_js

node_js:
  - 10.15.1

cache:
  directories:
    - node_modules

branches:
  only:
    - staging
    - master

before_script:
  - npm install

script:
  - if [[ "$TRAVIS_BRANCH" = "master" || "$TRAVIS_BRANCH" = "staging" ]]; then npm run build; else echo "not a build branch"; fi

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sed -i '/dist/d' .gitignore
  - git add . && git commit -m "latest build"
  
deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AKIAQSMMTZ6RUHYZYAOD}             // You have use environment variable name instead of plain text
    secret_access_key: ${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}     // You have use environment variable name instead of plain text
    region: "us-west-1"            // "ap-south-1"
    app: "spotify_mix_tape"                     // "demo-application"
    env: "<Spotifymixtape-env-1>"                     // "demo-production"
    bucket_name: "spotify-mix-tape-bucket" // Once you create new application, it will automatically create a unique bucket for it.
    on:
      branch: <main> // For example: - master

after_deploy:
  - echo "Applcation Deployed!"